apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-ms-dev
  name: orders-ms-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms-dev
  strategy: {}
  template:
    metadata:
      labels:
        app: orders-ms-dev
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/qehay-ms/qehay-image-register/orders-ms-dev
          name: orders-ms-dev
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats-dev"
            - name: QR_TOKEN_EXP
              value: "900"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: orders-ms-secrets
                  key: database_url
            - name: QR_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: orders-ms-secrets
                  key: qr_token_secret

          resources: {}
status: {}
