version: "3"
name: ecommerce-launcher-dev-v1.0.0

services:

  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.dev
    image: southamerica-east1-docker.pkg.dev/qehay-ms/qehay-image-register/client-gw-dev
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}


  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.dev
    image: southamerica-east1-docker.pkg.dev/qehay-ms/qehay-image-register/payments-ms-dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - CRYPTO_MASTER_KEY=${CRYPTO_MASTER_KEY}
      - CRYPTO_ALGORITHM=${CRYPTO_ALGORITHM}
      - PAYMENT_CONFIG_TABLE=${PAYMENT_CONFIG_TABLE}
  
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.dev
    image: southamerica-east1-docker.pkg.dev/qehay-ms/qehay-image-register/auth-ms-dev
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}



  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.dev
    image: southamerica-east1-docker.pkg.dev/qehay-ms/qehay-image-register/orders-ms-dev
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - QR_TOKEN_EXP=${QR_TOKEN_EXP}
      - QR_TOKEN_SECRET=${QR_TOKEN_SECRET}



  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.dev
    image: southamerica-east1-docker.pkg.dev/qehay-ms/qehay-image-register/products-ms-dev
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}
    
