version: "3"
name: ecommerce-launcher-local-v1.0.0

services:
  nats-server:
    image: nats:latest
    ports:
      - 8222:8222
  client-gateway:
    build: ./client-gateway
    image: client-gateway-local
    
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}



  payments-ms:
    build: ./payments-ms
    image: payments-ms-local
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - CRYPTO_MASTER_KEY=${CRYPTO_MASTER_KEY}
      - CRYPTO_ALGORITHM=${CRYPTO_ALGORITHM}
      - PAYMENT_CONFIG_TABLE=${PAYMENT_CONFIG_TABLE}


  
  auth-ms:
    build: ./auth-ms
    image: auth-ms-local 
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}



  orders-ms:
    build: ./orders-ms
    image: orders-ms-local
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - QR_TOKEN_EXP=${QR_TOKEN_EXP}
      - QR_TOKEN_SECRET=${QR_TOKEN_SECRET}

  products-ms:
    build: ./products-ms
    image: products-ms-local
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}

    
  
