apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats-dev
  name: nats-dev
spec:
  ports:
  - name: "4222"
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats-dev
  type: ClusterIP
status:
  loadBalancer: {}
